### ISSUE TITLE
BLAST Database error: No alias or index file found for nucleotide database

### ISSUE THREAD

**Issue by tpall** [avilab/vs#24]
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       megablast_nt
        1

[Sat Jan  5 17:02:06 2019]
rule megablast_nt:
    input: blast/SRR5580233_bac_unmapped_10_masked.fa, /gpfs/hpc/repository/VirusSeeker/databases/nt
    output: blast/SRR5580233_megablast_nt_10.tsv
    jobid: 0
    wildcards: sample=SRR5580233, n=10

Activating conda environment: /gpfs/hpc/home/taavi74/fastq/prjna361402/.snakemake/conda/76feaf1a
Traceback (most recent call last):
  File "/gpfs/hpc/home/taavi74/fastq/prjna361402/.snakemake/scripts/tmp2qetcyug.wrapper.py", line 30, in <module>
    run_blast(snakemake.input, snakemake.output, snakemake.params)
  File "/gpfs/hpc/home/taavi74/fastq/prjna361402/.snakemake/scripts/tmp2qetcyug.wrapper.py", line 27, in run_blast
    stdout, stderr = cline()
  File "/gpfs/hpc/home/taavi74/fastq/prjna361402/.snakemake/conda/76feaf1a/lib/python3.6/site-packages/Bio/Application/__init__.py", line 523, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 2 from "blastn -out blast/SRR5580233_megablast_nt_10.tsv -outfmt '6 qseqid sgi pident length mismatch gapopen qstart qend sstart send evalue bitscore' -show_gis -query blast/SRR5580233_bac_unmapped_10_masked.fa -db /gpfs/hpc/repository/VirusSeeker/databases/nt -evalue 1e-8 -word_size 16 -max_hsps 50 -num_threads 8 -task megablast", message 'BLAST Database error: No alias or index file found for nucleotide database [/gpfs/hpc/repository/VirusSeeker/databases/nt] in search path [/gpfs/hpc/home/taavi74/fastq/prjna361402::]'
[Sat Jan  5 17:02:07 2019]
Error in rule megablast_nt:
    jobid: 0
    output: blast/SRR5580233_megablast_nt_10.tsv
    conda-env: /gpfs/hpc/home/taavi74/fastq/prjna361402/.snakemake/conda/76feaf1a

RuleException:
CalledProcessError in line 164 of /gpfs/hpc/home/taavi74/Projects/vs/rules/blast.smk:
```

**Comment by tpall** [comment]
- Caused by this fix a405f9dcf1d9c594b9e15469c18e790e16a784df of pickling error where database path was placed under params or inputs in different rules.
- Solved by a5af957ac8874b7ae1caa40a9d15ec7aed8d9ac2
